# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3fd5baa19c2d2ba79ca1844eee846077be06305fa22cb1d6bf0695bfd1cc447446e8264ffba75cca9f70e257b67d329cef86eea94ff70bb09984d6bee18f8fdb

test:
  secret_key_base: cf701d6e01bd2325d36ef07adfb7823342808802ae2035a4270b6b56dc9290d5f5774847fb9645b1688152c3093124150e487165905f79f827fef196e4283cd3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
